### ISSUE TITLE
[@nstudio/nativescript-exoplayer][IOS] Explayer blocks back navigation

### ISSUE THREAD

**Issue by vicmasa** [nstudio/nativescript-plugins#110]
Adding Exoplayer to a view no longer allows navigation. This only happens on IOS, on Android this does not happen.

```
<Page xmlns="http://www.nativescript.org/tns.xsd"
    navigatingTo="navigatingTo"
    xmlns:Exoplayer="@nstudio/nativescript-exoplayer">
<StackLayout>
        <Label text="{{title}}" class="h2 black" />
        <Label text="{{subtitle}}" class="h4 black pm_l" textWrap="true" />
        <GridLayout width="{{width}}">
            <ActivityIndicator busy="true" />
            <Exoplayer:Video id="video" width="{{width}}" height="{{height}}" fill="true" />
        </GridLayout>
</StackLayout>
</Page>
```

```yaml
OS: macOS 13.0.1
CPU: (8) arm64 Apple M1 Pro
Shell: /bin/zsh
node: 19.2.0
npm: 8.19.3
nativescript: 8.4.0

# android
java: 11.0.17
ndk: Not Found
apis: Not Found
build_tools: Not Found
system_images: Not Found

# ios
xcode: 14.1/14B47b
cocoapods: 1.11.3
python: 2.7.18
python3: 3.9.6
ruby: 2.7.7
platforms: 
  - DriverKit 22.1
  - iOS 16.1
  - macOS 13.0
  - tvOS 16.1
  - watchOS 9.1
```

### Dependencies

```json
"dependencies": {
  "@nativescript/background-http": "^6.0.0",
  "@nativescript/camera": "^5.0.15",
  "@nativescript/core": "~8.4.0",
  "@nativescript/geolocation": "^8.1.0",
  "@nativescript/google-maps": "^1.4.9",
  "@nativescript/imagepicker": "^1.0.9",
  "@nativescript/social-share": "^2.3.0",
  "@nativescript/theme": "~3.0.2",
  "@nativescript/ui-charts": "^0.2.4",
  "@nstudio/nativescript-exoplayer": "^6.0.2",
  "@viia/nativescript-video-editor": "file:viia-nativescript-video-editor-1.0.0-picker-fix.tgz",
  "nativescript-sqlite": "^2.8.6",
  "nativescript-videoplayer": "^5.0.1"
},
"devDependencies": {
  "@nativescript/android": "8.4.0",
  "@nativescript/ios": "8.4.0",
  "@nativescript/webpack": "~5.0.12",
  "eslint": "^8.29.0"
}
```
